[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
